version: '3'
services:
  db:
    image: redis
    container_name: weeconn_db
    volumes:
      - ./redis-volume:/data
    expose:
      - 6379
  app:
    build: .
    container_name: weeconn
    restart: on-failure
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      GIN_MODE: release
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
